# Generated by Django 4.0.5 on 2022-06-25 05:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=2000, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='uploads/', verbose_name='Изображение')),
                ('price', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата созждания')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата редактирования')),
                ('publicated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('status', models.CharField(choices=[('accepted', 'Принято'), ('moderated', 'На модерации'), ('rejected', 'Отклонено')], default='moderated', max_length=25, verbose_name='Статус объявления')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Статус удаления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_user', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_category', to='webapp.category')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'db_table': 'announcement',
            },
        ),
    ]
